title: Cayman theme
description: Reducing uncertainty in brain tumor diagnosis using machine learning.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
